version: '3.7'

services:
  web:
    image: ruby:2.7
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      RAILS_ENV: development
      DATABASE_URL: sqlite3:///app/db/development.sqlite3
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
